use_frameworks!

target 'LPAActionSheetController_Example' do
  pod 'LPAActionSheetController', :path => '../'

  target 'LPAActionSheetController_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
